apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: qbshop-ingress
  namespace: qbshop
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - qbshop.asriv.shop
    secretName: qbshop-tls
  rules:
  - host: qbshop.asriv.shop
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: qbshop-service
            port:
              number: 80
